"""Phase 3b - repoint AvatarStudio references from C:\\1-AI\\APPS to C:\\APPS.

Only live, load-bearing files are rewritten. Historical records, snapshots and
regenerated artifacts are deliberately skipped: rewriting them would corrupt
the very evidence kept to recover from a bad migration, and would make the
usage archive claim a path that did not exist at the time.

Run with --apply to write; default is a dry run.
"""
import argparse
import json
import os
import re
import sys

sys.stdout.reconfigure(encoding="utf-8")

OLD = r"C:\1-AI\APPS\AvatarStudio"
NEW = r"C:\APPS\AvatarStudio"
OLD_FWD = "C:/1-AI/APPS/AvatarStudio"
NEW_FWD = "C:/APPS/AvatarStudio"

# Live files worth rewriting as plain text.
# qi_registry.json is handled separately: JSON escapes backslashes, so the on
# disk bytes are C:\\1-AI\\APPS\\AvatarStudio and a naive text replace of the
# single-backslash form silently matches nothing.
TARGETS = [
    r"C:\QIH\ecosystem\QI_Claude_Manager_Guide.md",
    r"C:\QIH\shared\documentation\project_library\_build_project_docs.py",
    r"C:\QIH\shared\documentation\project_library\AvatarStudio\source\status_intro.md",
    r"C:\QIH\shared\documentation\QI_Bot_Embodiment_Playbook.md",
    r"C:\QIH\shared\documentation\QI_Voice_Name_Fix_PROMPT.md",
]

# Never touch these, even if they match.
SKIP_MARKERS = (
    "usage_archive",              # historical transcripts
    "shared\\reports\\archive",   # session backfill snapshots
    "project_library_BACKUP",     # dated backup
    "migration_2026-08",          # this migration's own records
    "self_audits",                # point-in-time audits
    ".claude\\worktrees",         # git worktree duplicates
    "status.json",                # regenerated by the Hive
)


def skip(path):
    low = path.lower()
    return any(m.lower() in low for m in SKIP_MARKERS)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()

    total = 0
    for path in TARGETS:
        if not os.path.isfile(path):
            print("  MISSING  " + path)
            continue
        if skip(path):
            print("  SKIPPED  " + path)
            continue

        text = open(path, encoding="utf-8", errors="replace").read()
        n = text.count(OLD) + text.count(OLD_FWD)
        if not n:
            print("  no refs  " + path)
            continue

        total += n
        print("  %2d refs  %s" % (n, path))

        if args.apply:
            new_text = text.replace(OLD, NEW).replace(OLD_FWD, NEW_FWD)
            bak = path + ".bak-phase3"
            if not os.path.exists(bak):
                open(bak, "w", encoding="utf-8").write(text)
            open(path, "w", encoding="utf-8").write(new_text)
            print("           -> rewritten (.bak-phase3 kept)")

    print()
    print("total references %s: %d" % ("rewritten" if args.apply else "found", total))

    # ---- qi_registry.json: structural edit, not text substitution ----------
    reg = r"C:\QIH\ecosystem\qi_registry.json"
    print()
    print("qi_registry.json:")
    if os.path.isfile(reg):
        try:
            raw = open(reg, encoding="utf-8").read()
            d = json.loads(raw)
            changed = 0
            for pr in d.get("projects", []):
                if pr.get("id") != "avatarstudio":
                    continue
                for field in ("path", "original_path"):
                    v = pr.get(field)
                    if isinstance(v, str) and v.rstrip("\\").lower() == OLD.lower():
                        print("  %-14s %s -> %s" % (field, v, NEW))
                        if args.apply:
                            pr[field] = NEW
                        changed += 1
                paths = pr.get("paths")
                if isinstance(paths, dict):
                    for k, v in list(paths.items()):
                        if isinstance(v, str) and OLD.lower() in v.lower():
                            # A plain replacement string would have its
                            # backslashes read as regex escapes (\A etc), so
                            # substitute via a function instead.
                            nv = re.sub(re.escape(OLD), lambda _m: NEW,
                                        v, flags=re.I)
                            print("  paths.%-8s %s -> %s" % (k, v, nv))
                            if args.apply:
                                paths[k] = nv
                            changed += 1
            if not changed:
                print("  nothing to change")
            elif args.apply:
                bak = reg + ".bak-phase3"
                if not os.path.exists(bak):
                    open(bak, "w", encoding="utf-8").write(raw)
                with open(reg, "w", encoding="utf-8") as fh:
                    json.dump(d, fh, indent=2, ensure_ascii=False)
                    fh.write("\n")
                print("  -> registry rewritten (.bak-phase3 kept)")

            # verify
            d2 = json.load(open(reg, encoding="utf-8"))
            for pr in d2.get("projects", []):
                if pr.get("id") == "avatarstudio":
                    p = pr.get("path", "")
                    print("  now: path = %s   exists=%s" % (p, os.path.isdir(p)))
        except Exception as exc:                                # noqa: BLE001
            print("  registry handling failed: %r" % (exc,))

    if not args.apply:
        print()
        print("DRY RUN - re-run with --apply to write.")


if __name__ == "__main__":
    raise SystemExit(main())
