# -*- coding: utf-8 -*-
"""
Dashboard API Tests -- Tests for all Claude Manager dashboard endpoints.
Run: python -m pytest C:/Claude/Tests/test_dashboard_api.py -v
"""
import pytest
import httpx

BASE = "http://localhost:8600"
TIMEOUT = httpx.Timeout(10.0, connect=3.0)


@pytest.fixture(scope="module")
def client():
    with httpx.Client(base_url=BASE, timeout=TIMEOUT) as c:
        yield c


def skip_if_offline(client):
    try:
        client.get("/", timeout=httpx.Timeout(2.0))
    except (httpx.ConnectError, httpx.TimeoutException):
        pytest.skip("Dashboard is offline — skipping")


# ── Page routes ──────────────────────────────────────────────────────────────

def test_dashboard_home(client):
    skip_if_offline(client)
    r = client.get("/")
    assert r.status_code == 200
    assert "text/html" in r.headers.get("content-type", "")


def test_health_page(client):
    skip_if_offline(client)
    r = client.get("/health")
    assert r.status_code == 200
    assert "text/html" in r.headers.get("content-type", "")


def test_board_page(client):
    skip_if_offline(client)
    r = client.get("/board")
    assert r.status_code == 200
    assert "text/html" in r.headers.get("content-type", "")


def test_guide_page(client):
    skip_if_offline(client)
    r = client.get("/guide")
    assert r.status_code == 200
    assert "text/html" in r.headers.get("content-type", "")


# ── API endpoints ─────────────────────────────────────────────────────────────

def test_api_status(client):
    skip_if_offline(client)
    r = client.get("/api/status")
    assert r.status_code == 200
    data = r.json()
    assert "projects" in data


def test_api_agents(client):
    skip_if_offline(client)
    r = client.get("/api/agents")
    assert r.status_code == 200
    data = r.json()
    assert isinstance(data, dict)
    # Tester should now be in the roster
    expected_agents = {"architect", "builder", "scout", "scribe", "ops", "inspector", "tester"}
    for agent in expected_agents:
        assert agent in data, f"Agent '{agent}' missing from /api/agents"


def test_api_tasks_get(client):
    skip_if_offline(client)
    r = client.get("/api/tasks")
    assert r.status_code == 200
    data = r.json()
    assert "tasks" in data
    assert isinstance(data["tasks"], list)


def test_api_tasks_create_and_delete(client):
    """Full CRUD cycle: create a test task, verify it exists, then delete it."""
    skip_if_offline(client)

    # Create
    payload = {
        "title": "TEST TASK — auto-generated by test suite",
        "description": "This task was created by test_dashboard_api.py and should be deleted.",
        "project": "Claude_Manager",
        "agent": "tester",
        "priority": "low",
    }
    r = client.post("/api/tasks", json=payload)
    assert r.status_code == 200
    created = r.json()
    task_id = created.get("id")
    assert task_id, "Created task missing 'id' field"

    # Verify it's in the list
    r2 = client.get("/api/tasks")
    ids = [t["id"] for t in r2.json()["tasks"]]
    assert task_id in ids, "Created task not found in /api/tasks"

    # Move it
    r3 = client.patch(f"/api/tasks/{task_id}", json={"column": "done"})
    assert r3.status_code == 200

    # Delete
    r4 = client.delete(f"/api/tasks/{task_id}")
    assert r4.status_code == 200

    # Verify gone
    r5 = client.get("/api/tasks")
    ids_after = [t["id"] for t in r5.json()["tasks"]]
    assert task_id not in ids_after, "Deleted task still in /api/tasks"


def test_api_health_returns_projects(client):
    """Health API should return data for all registered projects."""
    skip_if_offline(client)
    r = client.get("/api/health")
    assert r.status_code == 200
    data = r.json()
    assert "projects" in data
    expected = {"Maia", "Naya", "NEXUS", "OpenClaw", "MQ", "Claude_Manager"}
    for proj in expected:
        assert proj in data["projects"], f"Project '{proj}' missing from /api/health"
