# -*- coding: utf-8 -*-
"""
QI War Room — agent responder (Phase N Stage 0.5).

The War Room chat persisted + displayed messages but nothing *answered*. This is
the responder: it watches warroom_messages for new HUMAN messages and posts a
reply from an agent persona, generated by the LOCAL LLM hub (NEXUS /synthesize) —
never Claude tokens (per the local-LLM-first rule).

Routing:
  - "@builder ..." / "@scout ..." etc. → that specific agent replies.
  - no mention                          → the host agent "hive" replies.

Loop-safety: only messages from humans (agent_id not in AGENT_IDS) get a reply,
so agent replies never trigger more agent replies.

Run standalone:   python qi_warroom_responder.py
Imported:         start_in_thread()  (used by the Hive Dashboard on startup)
"""
import json
import re
import time
import urllib.request
from pathlib import Path

try:
    from engine.common.qi_warroom import post, recent
except Exception:  # allow running from this folder directly
    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
    from engine.common.qi_warroom import post, recent

NEXUS_URL  = "http://127.0.0.1:8010/synthesize"
STATE_FILE = Path(r"C:\QIH\data\warroom_responder_state.json")
POLL_SECS  = 3.0
# Tried in order, first success wins — fast/reliable first, slow-local last.
# (groq currently rate-limits; mistral ~0.4s; gemma4 local ~19s fallback.)
PROVIDERS  = ["mistral", "gemma4", "groq"]
CONTEXT_N  = 12                # recent messages fed as conversation context

# Personas — one short system prompt per respondable agent.
PERSONAS = {
    "hive":      "You are Hive, the host coordinator of the QI War Room. Warm, concise, practical. "
                 "You help Renne and, when a question clearly belongs to a specialist, you say which "
                 "agent should take it (architect, builder, inspector, ops, scout, scribe, tester).",
    "architect": "You are Architect, the QI Hive system designer. You think in trade-offs, patterns, "
                 "and clean architecture. Concise and decisive.",
    "builder":   "You are Builder, the QI Hive implementation specialist. Practical, code-oriented, "
                 "you turn a clear plan into working steps. Concise.",
    "inspector": "You are Inspector, the QI standards & code-review enforcer. You flag risks, "
                 "compliance gaps, and quality issues plainly. Concise.",
    "ops":       "You are Ops, the QI service & infrastructure custodian. You speak in terms of "
                 "services, ports, logs, and health. Concise.",
    "scout":     "You are Scout, the QI fast-research agent. You give quick first-pass answers and "
                 "point to sources. Concise.",
    "scribe":    "You are Scribe, the QI documentation specialist. You summarize and record clearly. "
                 "Concise.",
    "tester":    "You are Tester, the QI cross-project test runner. You think about what could break "
                 "and how to verify it. Concise.",
}
AGENT_IDS = set(PERSONAS) | {"claude_code", "claude", "claude_work", "cowork"}
_MENTION  = re.compile(r"@(" + "|".join(PERSONAS) + r")\b", re.IGNORECASE)


def _load_last_id() -> int:
    try:
        return int(json.loads(STATE_FILE.read_text(encoding="utf-8")).get("last_id", 0))
    except Exception:
        return 0


def _save_last_id(v: int) -> None:
    try:
        STATE_FILE.write_text(json.dumps({"last_id": v}), encoding="utf-8")
    except Exception:
        pass


def _route(body: str) -> str:
    m = _MENTION.search(body or "")
    return m.group(1).lower() if m else "hive"


def generate_reply(agent_id: str, transcript: list[dict]) -> str | None:
    """Ask NEXUS for a reply in the given agent's voice. Returns text or None."""
    persona = PERSONAS.get(agent_id, PERSONAS["hive"])
    convo = "\n".join(f"{m.get('agent_label') or m.get('agent_id')}: {m.get('body')}"
                      for m in transcript[-CONTEXT_N:])
    prompt = (
        f"{persona}\n\n"
        f"This is the QI War Room group chat. Recent messages:\n{convo}\n\n"
        f"Reply as {agent_id.capitalize()} to the most recent message in 1-3 short "
        f"sentences. Plain text only — no preamble, no name prefix."
    )
    for provider in PROVIDERS:
        try:
            data = json.dumps({"prompt": prompt, "provider_ids": [provider],
                               "iterations": 1, "routing_mode": "parallel"}).encode()
            req = urllib.request.Request(NEXUS_URL, data=data,
                                         headers={"Content-Type": "application/json"}, method="POST")
            with urllib.request.urlopen(req, timeout=40) as r:
                out = json.loads(r.read().decode())
            # Don't surface NEXUS's own failure as if it were the agent talking.
            if int(out.get("success_count") or 0) < 1:
                continue
            text = (out.get("synthesis") or "").strip()
            if not text or text.lower().startswith("no successful responses"):
                continue
            return text
        except Exception:
            continue
    return None


def run_once(last_id: int) -> int:
    """Process any new human messages since last_id; return the new high-water id."""
    msgs = recent(50)
    new = [m for m in msgs if (m.get("id") or 0) > last_id]
    high = last_id
    for m in new:
        mid = m.get("id") or 0
        high = max(high, mid)
        author = (m.get("agent_id") or "").lower()
        if author in AGENT_IDS:
            continue  # an agent spoke — don't reply to agents (loop-safety)
        target = _route(m.get("body") or "")
        reply = generate_reply(target, msgs)
        if reply:
            post(target, reply)
    return high


def loop():
    last = _load_last_id()
    # On first run, don't reply to the entire backlog — start from the newest id.
    if last == 0:
        msgs = recent(1)
        last = (msgs[-1]["id"] if msgs else 0)
        _save_last_id(last)
    while True:
        try:
            high = run_once(last)
            if high != last:
                last = high
                _save_last_id(last)
        except Exception:
            pass
        time.sleep(POLL_SECS)


def start_in_thread():
    """Launch the responder loop as a daemon thread. Returns the Thread."""
    import threading
    t = threading.Thread(target=loop, name="warroom-responder", daemon=True)
    t.start()
    return t


if __name__ == "__main__":
    import sys
    sys.stdout.reconfigure(encoding="utf-8")
    print("[warroom-responder] starting loop (Ctrl-C to stop)…")
    loop()
